name: pull_request

on: pull_request

jobs:
  validate-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.5.0
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/HurSungYun/buf-github-actions-test.git#branch=main'
