name: pull_request

on: pull_request

jobs:
  validate-protos:
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.5.0
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: '.git#branch=main'
